// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package main

// Config for the little site that hosts the s99deploy binary for curl.
type Config struct {
	GinMode string `json:"gin_mode"`

	ListenAddr string `json:"listen_addr"`

	// The CLI binary served at /s99deploy, built by the deploy alongside the
	// site binary. Relative to the working directory (the app checkout).
	BinPath string `json:"bin_path"`

	// Whose X-Forwarded-Proto is believed when building the URLs printed by /
	// and /install.sh. Empty trusts nobody.
	TrustedProxies []string `json:"trusted_proxies"`
}
