// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package site

// Config for the little site that hosts the depl binary for curl.
type Config struct {
	GinMode string `json:"gin_mode"`

	ListenAddr string `json:"listen_addr"`

	// The CLI binary served at /depl, relative to the working directory.
	BinPath string `json:"bin_path"`

	// Peers trusted for X-Forwarded-Proto and gin ClientIP: addresses or CIDR blocks; empty trusts nobody.
	TrustedProxies []string `json:"trusted_proxies"`
}
