// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package manifest

// The per-app deploy definition, read from deploy.json in the app repo root.
type Manifest struct {
	// Service name: the systemd unit, the system user, and /opt/<name>.
	Name string `json:"name"`

	// Shell commands run in order as the service user in the app dir.
	Build []string `json:"build"`

	// Argv exec'd by systemd through `s99deploy run`. argv[0] with a path
	// separator is resolved relative to the app dir; a bare name through PATH.
	Run []string `json:"run"`

	// Extra environment for build and run (e.g. CONFIG_PATH).
	Env map[string]string `json:"env"`

	// Vars that must be non-empty in the build environment (usually from .env).
	RequireEnv []string `json:"require_env"`

	// Post-deploy health check on loopback.
	Check Check `json:"check"`
}

type Check struct {
	Port int64 `json:"port"`

	Path string `json:"path"`

	TimeoutSeconds int64 `json:"timeout_seconds"`
}
