// Code generated by loc. DO NOT EDIT.

package messages

// Keys, for call sites that need the string rather than the accessor.
const (
	KeyCliCommandColorFlag       = "cli.command.colorFlag"
	KeyCliCommandCommands        = "cli.command.commands"
	KeyCliCommandCompletionShort = "cli.command.completionShort"
	KeyCliCommandConfigFlag      = "cli.command.configFlag"
	KeyCliCommandFlags           = "cli.command.flags"
	KeyCliCommandGlobalFlags     = "cli.command.globalFlags"
	KeyCliCommandHelpFlag        = "cli.command.helpFlag"
	KeyCliCommandHelpHint        = "cli.command.helpHint"
	KeyCliCommandHelpShort       = "cli.command.helpShort"
	KeyCliCommandInstallShort    = "cli.command.installShort"
	KeyCliCommandInterrupted     = "cli.command.interrupted"
	KeyCliCommandInvalidLanguage = "cli.command.invalidLanguage"
	KeyCliCommandLangFlag        = "cli.command.langFlag"
	KeyCliCommandNextSteps       = "cli.command.nextSteps"
	KeyCliCommandPurgeFlag       = "cli.command.purgeFlag"
	KeyCliCommandRootLong        = "cli.command.rootLong"
	KeyCliCommandRootShort       = "cli.command.rootShort"
	KeyCliCommandRunShort        = "cli.command.runShort"
	KeyCliCommandServeShort      = "cli.command.serveShort"
	KeyCliCommandShellShort      = "cli.command.shellShort"
	KeyCliCommandSiteShort       = "cli.command.siteShort"
	KeyCliCommandTimeoutFlag     = "cli.command.timeoutFlag"
	KeyCliCommandUninstallShort  = "cli.command.uninstallShort"
	KeyCliCommandUpShort         = "cli.command.upShort"
	KeyCliCommandUsage           = "cli.command.usage"
	KeyCliCommandVerboseFlag     = "cli.command.verboseFlag"
	KeyCliCommandVersionFlag     = "cli.command.versionFlag"
	KeyCliCommandYesFlag         = "cli.command.yesFlag"
	KeyCliConfirmAborted         = "cli.confirm.aborted"
	KeyCliConfirmPurgeAlso       = "cli.confirm.purgeAlso"
	KeyCliConfirmRemovesService  = "cli.confirm.removesService"
	KeyCliConfirmTypeToConfirm   = "cli.confirm.typeToConfirm"
	KeyLogsBuilding              = "logs.building"
	KeyLogsCheckoutPresent       = "logs.checkoutPresent"
	KeyLogsCloning               = "logs.cloning"
	KeyLogsCreatedEnv            = "logs.createdEnv"
	KeyLogsDeployed              = "logs.deployed"
	KeyLogsInstalled             = "logs.installed"
	KeyLogsListening             = "logs.listening"
	KeyLogsPulling               = "logs.pulling"
	KeyLogsPurged                = "logs.purged"
	KeyLogsRestarting            = "logs.restarting"
	KeyLogsStopping              = "logs.stopping"
	KeyLogsUninstalled           = "logs.uninstalled"
)

// DefaultLocale is the locale a missing translation falls back to.
const DefaultLocale = "en"

// Locales are every locale this catalogue was built for, in config order.
var Locales = []string{
	"en",
	"pl",
}
