// Code generated by loc. DO NOT EDIT.

package messages

import "github.com/nicksnyder/go-i18n/v2/i18n"

func plain(l *i18n.Localizer, id string) string {
	out, err := l.Localize(&i18n.LocalizeConfig{MessageID: id})
	if err != nil {
		// The raw key is visibly wrong; an empty string reads as a blank label.
		return id
	}
	return out
}

func withData(l *i18n.Localizer, id string, data map[string]any) string {
	out, err := l.Localize(&i18n.LocalizeConfig{MessageID: id, TemplateData: data})
	if err != nil {
		return id
	}
	return out
}

func withCount(l *i18n.Localizer, id string, count int, data map[string]any) string {
	out, err := l.Localize(&i18n.LocalizeConfig{
		MessageID:    id,
		TemplateData: data,
		PluralCount:  count,
	})
	if err != nil {
		return id
	}
	return out
}

// CliCommandColorFlag Help for --color.
func CliCommandColorFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.colorFlag")
}

// CliCommandCommands The available-commands label in cobra's help template.
func CliCommandCommands(l *i18n.Localizer) string {
	return plain(l, "cli.command.commands")
}

// CliCommandCompletionShort Description of cobra's built-in completion command.
func CliCommandCompletionShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.completionShort")
}

// CliCommandConfigFlag Help for the site's --config.
func CliCommandConfigFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.configFlag")
}

// CliCommandFlags The local-flags label in cobra's help template.
func CliCommandFlags(l *i18n.Localizer) string {
	return plain(l, "cli.command.flags")
}

// CliCommandGlobalFlags The inherited-flags label in cobra's help template.
func CliCommandGlobalFlags(l *i18n.Localizer) string {
	return plain(l, "cli.command.globalFlags")
}

// CliCommandHelpFlag Help for cobra's --help.
func CliCommandHelpFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.helpFlag")
}

// CliCommandHelpHint The closing line of the help template.
type CliCommandHelpHintParams struct {
	Command string
}

func CliCommandHelpHint(l *i18n.Localizer, p CliCommandHelpHintParams) string {
	data := map[string]any{
		"Command": p.Command,
	}
	return withData(l, "cli.command.helpHint", data)
}

// CliCommandHelpShort Description of cobra's built-in help command.
func CliCommandHelpShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.helpShort")
}

// CliCommandInstallShort One-line description of the install command.
func CliCommandInstallShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.installShort")
}

// CliCommandInterrupted The single line an interrupted run prints.
type CliCommandInterruptedParams struct {
	Name string
}

func CliCommandInterrupted(l *i18n.Localizer, p CliCommandInterruptedParams) string {
	data := map[string]any{
		"Name": p.Name,
	}
	return withData(l, "cli.command.interrupted", data)
}

// CliCommandInvalidColor Usage error for an unsupported --color.
type CliCommandInvalidColorParams struct {
	Value string
}

func CliCommandInvalidColor(l *i18n.Localizer, p CliCommandInvalidColorParams) string {
	data := map[string]any{
		"Value": p.Value,
	}
	return withData(l, "cli.command.invalidColor", data)
}

// CliCommandInvalidLanguage Usage error for an unsupported --lang.
type CliCommandInvalidLanguageParams struct {
	Supported string
	Value     string
}

func CliCommandInvalidLanguage(l *i18n.Localizer, p CliCommandInvalidLanguageParams) string {
	data := map[string]any{
		"Supported": p.Supported,
		"Value":     p.Value,
	}
	return withData(l, "cli.command.invalidLanguage", data)
}

// CliCommandLangFlag Help for --lang.
func CliCommandLangFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.langFlag")
}

// CliCommandNextSteps What install prints when it finishes.
type CliCommandNextStepsParams struct {
	Name string
	Root string
}

func CliCommandNextSteps(l *i18n.Localizer, p CliCommandNextStepsParams) string {
	data := map[string]any{
		"Name": p.Name,
		"Root": p.Root,
	}
	return withData(l, "cli.command.nextSteps", data)
}

// CliCommandPurgeFlag Help for uninstall --purge.
func CliCommandPurgeFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.purgeFlag")
}

// CliCommandRootLong The paragraph shown above the command list.
func CliCommandRootLong(l *i18n.Localizer) string {
	return plain(l, "cli.command.rootLong")
}

// CliCommandRootShort One-line description of s99deploy.
func CliCommandRootShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.rootShort")
}

// CliCommandRunShort One-line description of the run command, which systemd calls.
func CliCommandRunShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.runShort")
}

// CliCommandServeShort One-line description of the site's serve command.
func CliCommandServeShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.serveShort")
}

// CliCommandShellShort Description of one completion subcommand.
type CliCommandShellShortParams struct {
	Shell string
}

func CliCommandShellShort(l *i18n.Localizer, p CliCommandShellShortParams) string {
	data := map[string]any{
		"Shell": p.Shell,
	}
	return withData(l, "cli.command.shellShort", data)
}

// CliCommandSiteShort One-line description of the site binary.
func CliCommandSiteShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.siteShort")
}

// CliCommandTimeoutFlag Help for up --timeout.
func CliCommandTimeoutFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.timeoutFlag")
}

// CliCommandUninstallShort One-line description of the uninstall command.
func CliCommandUninstallShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.uninstallShort")
}

// CliCommandUpShort One-line description of the up command.
func CliCommandUpShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.upShort")
}

// CliCommandUsage The Usage label in cobra's help template.
func CliCommandUsage(l *i18n.Localizer) string {
	return plain(l, "cli.command.usage")
}

// CliCommandVerboseFlag Help for --verbose.
func CliCommandVerboseFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.verboseFlag")
}

// CliCommandVersionFlag Help for cobra's --version.
func CliCommandVersionFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.versionFlag")
}

// CliCommandYesFlag Help for uninstall --yes.
func CliCommandYesFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.yesFlag")
}

// CliConfirmAborted Error when the typed name did not match.
func CliConfirmAborted(l *i18n.Localizer) string {
	return plain(l, "cli.confirm.aborted")
}

// CliConfirmPurgeAlso Second line, shown only for --purge.
type CliConfirmPurgeAlsoParams struct {
	Name string
	Root string
}

func CliConfirmPurgeAlso(l *i18n.Localizer, p CliConfirmPurgeAlsoParams) string {
	data := map[string]any{
		"Name": p.Name,
		"Root": p.Root,
	}
	return withData(l, "cli.confirm.purgeAlso", data)
}

// CliConfirmRemovesService First line of the uninstall confirmation.
type CliConfirmRemovesServiceParams struct {
	Name string
}

func CliConfirmRemovesService(l *i18n.Localizer, p CliConfirmRemovesServiceParams) string {
	data := map[string]any{
		"Name": p.Name,
	}
	return withData(l, "cli.confirm.removesService", data)
}

// CliConfirmTypeToConfirm The prompt itself; the reader types the app name.
type CliConfirmTypeToConfirmParams struct {
	Name string
}

func CliConfirmTypeToConfirm(l *i18n.Localizer, p CliConfirmTypeToConfirmParams) string {
	data := map[string]any{
		"Name": p.Name,
	}
	return withData(l, "cli.confirm.typeToConfirm", data)
}

// CliStatusFailed State word for a step that did not finish.
func CliStatusFailed(l *i18n.Localizer) string {
	return plain(l, "cli.status.failed")
}

// CliStatusOk State word for a step that finished.
func CliStatusOk(l *i18n.Localizer) string {
	return plain(l, "cli.status.ok")
}

// CliStatusRunning State word for a step that is running now.
func CliStatusRunning(l *i18n.Localizer) string {
	return plain(l, "cli.status.running")
}

// CliStatusSkipped State word for a step that had nothing to do.
func CliStatusSkipped(l *i18n.Localizer) string {
	return plain(l, "cli.status.skipped")
}

// CliStatusStale State word for output that no longer matches its source.
func CliStatusStale(l *i18n.Localizer) string {
	return plain(l, "cli.status.stale")
}

// CliStatusWaiting State word for a step that has not started.
func CliStatusWaiting(l *i18n.Localizer) string {
	return plain(l, "cli.status.waiting")
}

// CliStatusWarning State word for a line that reports something suspicious.
func CliStatusWarning(l *i18n.Localizer) string {
	return plain(l, "cli.status.warning")
}

// LogsBuilding Log event: one build command from the manifest is running.
func LogsBuilding(l *i18n.Localizer) string {
	return plain(l, "logs.building")
}

// LogsCheckoutPresent Log event: install found a checkout already in place and kept it.
func LogsCheckoutPresent(l *i18n.Localizer) string {
	return plain(l, "logs.checkoutPresent")
}

// LogsCloning Log event: the repository is being cloned.
func LogsCloning(l *i18n.Localizer) string {
	return plain(l, "logs.cloning")
}

// LogsCreatedEnv Log event: the environment file was created on first install.
func LogsCreatedEnv(l *i18n.Localizer) string {
	return plain(l, "logs.createdEnv")
}

// LogsDeployed Log event: the deploy finished and the app answered its health check.
func LogsDeployed(l *i18n.Localizer) string {
	return plain(l, "logs.deployed")
}

// LogsHealthCheck Log event: the deploy is waiting for the app to answer its health check.
func LogsHealthCheck(l *i18n.Localizer) string {
	return plain(l, "logs.healthCheck")
}

// LogsInstalled Log event: install finished.
func LogsInstalled(l *i18n.Localizer) string {
	return plain(l, "logs.installed")
}

// LogsListening Log event: the site is listening.
func LogsListening(l *i18n.Localizer) string {
	return plain(l, "logs.listening")
}

// LogsPulling Log event: the checkout is being fast-forwarded.
func LogsPulling(l *i18n.Localizer) string {
	return plain(l, "logs.pulling")
}

// LogsPurged Log event: the unit, the tree and the account are gone.
func LogsPurged(l *i18n.Localizer) string {
	return plain(l, "logs.purged")
}

// LogsRestarting Log event: the unit is being restarted.
func LogsRestarting(l *i18n.Localizer) string {
	return plain(l, "logs.restarting")
}

// LogsStopping Log event: a signal arrived and the site stopped accepting.
func LogsStopping(l *i18n.Localizer) string {
	return plain(l, "logs.stopping")
}

// LogsUninstalled Log event: the unit is gone and the tree was kept.
func LogsUninstalled(l *i18n.Localizer) string {
	return plain(l, "logs.uninstalled")
}
